### ISSUE TITLE
Installing yara-python package : “OSError - cannot open shared file”

### ISSUE THREAD

**Issue by radheshkrishnan** [plusvic/yara#301]
I am trying to install yara-python in ubuntu 14.10 (64 bit).  When I try to import yara from python terminal I am getting following error:

Failed to import '/usr/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games;/usr/lib
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python2.7/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python2.7/dist-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libyara.so: cannot open shared object file: No such file or directory

I have added path "/usr/local/lib" to "/etc/ld.so.conf" file and ran ldconfig. Still am getting above error.

**Comment by plusvic** [comment]
Did you follow the instructions at http://yara.readthedocs.org/en/v3.3.0/gettingstarted.html?
